### ISSUE TITLE
能否增加去开屏和切换多任务后的广告

### ISSUE THREAD

**Issue by Elflare** [GuhDoy/TiebaTS#10]
启动一个开屏广告, 切出去切回来再来一次, 贴吧是真的恶心

**Comment by GuhDoy** [comment]
已实现

 [https://github.com/GuhDoy/TiebaTS/blob/4357a5fdb19bc0486839baeabab1a1ed01f70b16/app/src/main/java/gm/tieba/tabswitch/hooker/minus/Purify.java#L93](url) 

[https://github.com/GuhDoy/TiebaTS/blob/4357a5fdb19bc0486839baeabab1a1ed01f70b16/app/src/main/java/gm/tieba/tabswitch/hooker/minus/Purify.java#L103](url)
