### ISSUE TITLE
12.19.1.0使用ts有警告提示

### ISSUE THREAD

**Issue by kuu-an** [GuhDoy/TiebaTS#25]
![Screenshot_2022-05-31-07-47-08-584_com baidu tieba](https://user-images.githubusercontent.com/62643663/171068847-9cf886fe-c4f7-4af6-8ff7-b962ba221da5.jpg)
上一个新版本提示说已适应12.19.1.10版本，所以我去豌豆荚下载了旧版本，结果现在提示需要反混淆，而且还失败了，这是什么情况？
![Screenshot_2022-05-31-07-49-25-167_com miui securitycenter](https://user-images.githubusercontent.com/62643663/171068940-aeebe7eb-de4a-413f-b8f1-9719cc0f2052.jpg)

**Comment by GuhDoy** [comment]
新版模块不支持旧版贴吧
