### ISSUE TITLE
这是配置没有清理干净导致任何版本都不能用吗？

### ISSUE THREAD

**Issue by naoki66** [GuhDoy/TiebaTS#28]
![Screenshot_20221008-141016.png](https://user-images.githubusercontent.com/22931306/194692089-513aae90-bbdc-4e22-92b0-3ad0f580dee5.png)
![Screenshot_20221007-011742.png](https://user-images.githubusercontent.com/22931306/194692096-2076be52-d6ba-4bf3-9354-bb58e0dea1fe.png)

之前任何内置版本都可以用，内置2.7.2。
看到re发了2.8.2测试版，想着自己做一个内置，结果失败。退回用别人的内置版，不管什么版本都失败。

**Comment by GuhDoy** [comment]
这是因为无法从系统返回的安装包路径获取到贴吧的dex。可能是使用了加固的贴吧，建议使用官方版本制作内置版。
